version: '3'
services:
  order-service:
    image: fandi23/order-service:latest
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      AMQP_URL: "amqp://localhost:15672"
  shipping-service:
    image: fandi23/shipping-service:latest
    depends_on:
      - order-service
    environment:
      PORT: 3001
      AMQP_URL: "amqp://localhost:15672"
  rabbitmq:
    image: rabbitmq:3.11-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "arzyadwan"
      RABBITMQ_DEFAULT_PASS: "andhy060402"
